const $ = (s) => document.querySelector(s);
const toast = (message) => { const el = $('#toast'); el.textContent = message; el.classList.add('show'); setTimeout(() => el.classList.remove('show'), 2600); };
const savedGoalProgress = Number(localStorage.getItem('pocketPalGoalProgress') || 64);
const savedBalance = localStorage.getItem('pocketPalBalance');
const savedIncome = localStorage.getItem('pocketPalIncome');
const savedOutgo = localStorage.getItem('pocketPalOutgo');
if (savedBalance) $('#balance').textContent = `$${Number(savedBalance).toFixed(2)}`;
if (savedIncome) $('#income').textContent = `$${Number(savedIncome).toFixed(2)}`;
if (savedOutgo) $('#outgo').textContent = `$${Number(savedOutgo).toFixed(2)}`;
document.querySelector('.goal-bar i').style.width = `${savedGoalProgress}%`;
document.querySelector('.donut').style.setProperty('--progress', `${savedGoalProgress}%`);
const modal = $('#guideModal');
function openGuide(){ modal.classList.add('open'); modal.setAttribute('aria-hidden','false'); }
function closeGuide(){ modal.classList.remove('open'); modal.setAttribute('aria-hidden','true'); }
$('#openGuide').addEventListener('click', openGuide); $('#openGuideTop').addEventListener('click', openGuide); $('#closeGuide').addEventListener('click', closeGuide); $('#gotIt').addEventListener('click', closeGuide);
modal.addEventListener('click', e => { if(e.target === modal) closeGuide(); });
document.addEventListener('keydown', e => { if(e.key === 'Escape') closeGuide(); });
$('.mobile-menu').addEventListener('click', () => $('.sidebar').classList.toggle('open'));
document.querySelectorAll('.nav-link').forEach(link => link.addEventListener('click', () => $('.sidebar').classList.remove('open')));
const chartStyles = document.createElement('style'); chartStyles.textContent = `.analytics-grid{display:grid;grid-template-columns:1fr 1.45fr;gap:17px;margin-top:17px}.analytics-card{background:#fff;border:1px solid #efedf2;border-radius:16px;padding:22px;box-shadow:0 9px 25px #41416708}.chart-title{font:600 19px Fredoka;margin:0}.chart-subtitle{font-size:11px;color:#a4a2b0;margin:5px 0 18px}.pie-wrap{display:flex;align-items:center;gap:21px}.pie{width:126px;height:126px;border-radius:50%;background:conic-gradient(#7667e8 0 68%,#f27c70 68% 84%,#f8d479 84% 100%);position:relative;flex-shrink:0}.pie:after{content:'';position:absolute;inset:29px;background:#fff;border-radius:50%}.legend{font-size:11px;color:#77758e;line-height:2}.legend span{display:inline-block;width:8px;height:8px;border-radius:3px;margin-right:7px}.legend b{color:#292c4b;display:block}.trend-chart{width:100%;height:147px;display:block}.chart-legend{display:flex;gap:15px;font-size:10px;color:#9997a8;margin-top:3px}.chart-legend i{width:8px;height:8px;background:#7667e8;border-radius:50%;display:inline-block;margin-right:5px}.chart-legend .up{color:#39aa82;margin-left:auto;font-weight:700}@media(max-width:800px){.analytics-grid{grid-template-columns:1fr}}`; document.head.appendChild(chartStyles);
function renderAnalytics(){ const old = document.querySelector('.analytics-grid'); if(old) old.remove(); const income = parseFloat($('#income').textContent.replace('$','')); const out = parseFloat($('#outgo').textContent.replace('$','')); const balance = parseFloat($('#balance').textContent.replace('$','')); const total = Math.max(income + out, 1); const incomePct = Math.round(income / total * 100); const outPct = 100 - incomePct; const trend = balance >= 0 ? '↗' : '↘'; const section = document.createElement('section'); section.className='analytics-grid'; section.innerHTML = `<article class="analytics-card" tabindex="0" role="button" aria-label="View money activity"><p class="eyebrow">MONEY MIX</p><h2 class="chart-title">Where it’s going</h2><p class="chart-subtitle">Live from your money trail · click to view activity</p><div class="pie-wrap"><div class="pie" style="background:conic-gradient(#7667e8 0 ${incomePct}%,#f27c70 ${incomePct}% 100%)"></div><div class="legend"><b><span style="background:#7667e8"></span>Money in ${incomePct}%</b><span style="background:#f27c70"></span>Money out ${outPct}%<br><small>$${income.toFixed(2)} earned · $${out.toFixed(2)} spent</small></div></div></article><article class="analytics-card" tabindex="0" role="button" aria-label="View balance activity"><p class="eyebrow">BALANCE VIBES</p><h2 class="chart-title">Your balance: $${balance.toFixed(2)} <span style="color:#39aa82;font-size:14px">${trend}</span></h2><p class="chart-subtitle">Based on the balance in your tracker · click to view activity</p><svg class="trend-chart" viewBox="0 0 520 150" role="img" aria-label="Balance trend graph"><path d="M22 122 H505 M22 86 H505 M22 50 H505" stroke="#f0eef5" stroke-width="1"/><path d="M22 112 C75 108 85 96 125 101 S180 74 220 85 S274 53 315 66 S370 48 406 52 S462 22 505 27" fill="none" stroke="#7667e8" stroke-width="4" stroke-linecap="round"/><path d="M22 112 C75 108 85 96 125 101 S180 74 220 85 S274 53 315 66 S370 48 406 52 S462 22 505 27 L505 135 L22 135Z" fill="#7667e8" opacity=".08"/><circle cx="505" cy="27" r="5" fill="#fff" stroke="#7667e8" stroke-width="3"/><text x="20" y="148" fill="#aaa8b5" font-size="10">Last week</text><text x="460" y="148" fill="#aaa8b5" font-size="10">Today</text></svg><div class="chart-legend"><span><i></i>Balance trend</span><span class="up">${trend} Live tracker balance</span></div></article>`; $('.middle-grid').before(section); section.querySelectorAll('.analytics-card').forEach(card => { card.addEventListener('click', () => { $('#activity').scrollIntoView({behavior:'smooth'}); toast('Here’s the activity behind this visual! 👀'); }); card.addEventListener('keydown', e => { if(e.key === 'Enter' || e.key === ' ') card.click(); }); }); }
renderAnalytics();
$('#addToGoal').addEventListener('click', () => { toast('Nice! $10 added to your headphones goal 🎧'); const bar = document.querySelector('.goal-bar i'); bar.style.width = '67%'; document.querySelector('.donut').style.setProperty('--progress','67%'); localStorage.setItem('pocketPalGoalProgress','67'); });
$('#logMoment').addEventListener('click', () => { toast('One more money moment to go! ✨'); document.querySelector('.quest-progress i').style.width='100%'; document.querySelector('.quest-progress span').textContent='3 / 3 found'; });
$('#paidBtn').addEventListener('click', () => toast('Pick a bill above, then mark it paid! ✅'));
const jordanRow = [...document.querySelectorAll('.bill-row')].find(row => row.textContent.includes('Jordan'));
if (jordanRow) { const complete = document.createElement('button'); complete.textContent = '✓'; complete.setAttribute('aria-label', 'Mark Jordan IOU as completed'); complete.style.cssText = 'border:1px solid #d8d5e8;background:#fff;color:#aaa7b7;border-radius:7px;width:25px;height:25px;font-weight:700;cursor:pointer'; jordanRow.appendChild(complete); complete.addEventListener('click', () => { const completed = jordanRow.classList.toggle('completed'); jordanRow.style.opacity = completed ? '.55' : '1'; jordanRow.querySelectorAll('strong,small,b').forEach(el => el.style.textDecoration = completed ? 'line-through' : 'none'); complete.style.background = completed ? '#43bd91' : '#fff'; complete.style.borderColor = completed ? '#43bd91' : '#d8d5e8'; complete.style.color = completed ? '#fff' : '#aaa7b7'; complete.setAttribute('aria-label', completed ? 'Mark Jordan IOU as incomplete' : 'Mark Jordan IOU as completed'); toast(completed ? 'Jordan IOU marked as complete! 🎉' : 'Jordan IOU added back to your list.'); }); }
$('#viewAll').addEventListener('click', () => toast('You’re all caught up — showing your latest 3 moments.'));
$('#addForm').addEventListener('submit', (e) => { e.preventDefault(); const name=$('#itemName').value.trim(); const amount=Number($('#itemAmount').value); const type=$('#itemType').value; if(!name||!amount)return; const row=document.createElement('div'); row.className='activity-row'; row.innerHTML=`<span class="activity-icon ${type==='in'?'green':'coral'}">${type==='in'?'💫':'🧾'}</span><div><strong>${name}</strong><small>Just now · Money ${type==='in'?'in':'out'}</small></div><b class="amount ${type==='in'?'positive':'negative'}">${type==='in'?'+':'−'}$${amount.toFixed(2)}</b>`; $('#activityList').prepend(row); let balance=parseFloat($('#balance').textContent.replace('$','').replace(',','')); balance += type==='in'?amount:-amount; $('#balance').textContent=`$${balance.toFixed(2)}`; const total = type==='in' ? $('#income') : $('#outgo'); let current = parseFloat(total.textContent.replace('$','').replace(',','')); current += amount; total.textContent = `$${current.toFixed(2)}`; localStorage.setItem('pocketPalBalance', balance); localStorage.setItem(type==='in' ? 'pocketPalIncome' : 'pocketPalOutgo', current); renderAnalytics(); $('#itemName').value=''; $('#itemAmount').value=''; toast(type==='in'?'Money added to your trail! 💸':'Spend logged — you’ve got this! 🌟'); });
